language: python
python:
    - 3.5
    - 3.6
    - nightly
os:
    - linux
install:
  	- sudo apt install graphviz graphviz-dev
  	- pip3 install -r requirements.txt
script:
    - make test
    - make readme.md
    - cat readme.md
