language: python
python:
    - 3.5
    - 3.6
    - 3.7
os:
    - linux
before_install:
    - sudo apt install graphviz graphviz-dev
install:
    - pip3 install -r requirements.txt
script:
    - make test
    - make readme.md
    - cat readme.md
